/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/auth/register": {
    post: operations["AuthController_register"];
  };
  "/auth/login": {
    post: operations["AuthController_login"];
  };
  "/auth/logout": {
    post: operations["AuthController_logout"];
  };
  "/auth/forgot-password": {
    post: operations["AuthController_forgotPassword"];
  };
  "/auth/reset-password": {
    post: operations["AuthController_resetPassword"];
  };
  "/auth/verify-email": {
    post: operations["AuthController_verifyEmail"];
  };
  "/auth/resend-verification": {
    post: operations["AuthController_resendVerification"];
  };
  "/auth/me": {
    get: operations["AuthController_me"];
  };
  "/orchestration/start": {
    post: operations["OrchestratorController_start"];
  };
  "/orchestration/cancel": {
    post: operations["OrchestratorController_cancel"];
  };
  "/orchestration/decision": {
    post: operations["OrchestratorController_decide"];
  };
  "/vaults": {
    get: operations["VaultsController_list"];
    post: operations["VaultsController_create"];
  };
  "/vaults/{id}": {
    get: operations["VaultsController_get"];
  };
  "/vaults/{id}/settings": {
    patch: operations["VaultsController_updateSettings"];
  };
  "/verifiers": {
    get: operations["VerifiersController_list"];
  };
  "/verifiers/invitations": {
    post: operations["VerifiersController_invite"];
  };
  "/verifiers/invitations/preview": {
    /** Адрес и признак аккаунта по токену приглашения (без входа) */
    post: operations["VerifiersController_preview"];
  };
  "/verifiers/invitations/accept": {
    post: operations["VerifiersController_accept"];
  };
  "/verifiers/invitations/{invitationId}": {
    delete: operations["VerifiersController_revokeInvitation"];
  };
  "/verifiers/{vaultId}/{userId}/revoke": {
    post: operations["VerifiersController_revokeMember"];
  };
  "/verification-events": {
    get: operations["VerificationEventsController_list"];
    post: operations["VerificationEventsController_start"];
  };
  "/verification-events/{id}": {
    get: operations["VerificationEventsController_get"];
  };
  "/verification-events/{id}/cancel": {
    post: operations["VerificationEventsController_cancel"];
  };
  "/verification-events/{id}/confirm": {
    post: operations["VerificationEventsController_confirm"];
  };
  "/verification-events/{id}/deny": {
    post: operations["VerificationEventsController_deny"];
  };
  "/blocks": {
    get: operations["BlocksController_list"];
    post: operations["BlocksController_create"];
  };
  "/blocks/{id}": {
    get: operations["BlocksController_get"];
    delete: operations["BlocksController_remove"];
  };
  "/blocks/{id}/recipients": {
    /** List recipients assigned to a block */
    get: operations["BlocksController_listRecipients"];
    /** Assign a recipient to a block */
    post: operations["BlocksController_assignRecipient"];
  };
  "/recipients": {
    get: operations["RecipientsController_search"];
    post: operations["RecipientsController_create"];
  };
  "/recipients/me/key": {
    put: operations["RecipientsController_claimKey"];
  };
  "/recipients/{id}/confirm-key": {
    post: operations["RecipientsController_confirmKey"];
  };
  "/blocks/{id}/public": {
    get: operations["PublicLinksController_get"];
    put: operations["PublicLinksController_upsert"];
    delete: operations["PublicLinksController_disable"];
  };
  "/vaults/{vaultId}/heartbeat": {
    get: operations["HeartbeatsController_getConfig"];
    patch: operations["HeartbeatsController_updateConfig"];
  };
  "/heartbeats/ping": {
    post: operations["HeartbeatsController_ping"];
  };
  "/healthz": {
    get: operations["HealthController_healthz"];
  };
  "/readyz": {
    get: operations["HealthController_readyz"];
  };
  "/users": {
    get: operations["UsersController_list"];
    post: operations["UsersController_create"];
  };
  "/users/{id}": {
    get: operations["UsersController_get"];
    delete: operations["UsersController_remove"];
    patch: operations["UsersController_update"];
  };
  "/plans": {
    get: operations["PlansController_list"];
    post: operations["PlansController_create"];
  };
  "/plans/{id}": {
    get: operations["PlansController_get"];
    delete: operations["PlansController_remove"];
    patch: operations["PlansController_update"];
  };
  "/subscriptions": {
    get: operations["SubscriptionsController_list"];
    post: operations["SubscriptionsController_create"];
  };
  "/subscriptions/{id}": {
    get: operations["SubscriptionsController_get"];
    delete: operations["SubscriptionsController_remove"];
    patch: operations["SubscriptionsController_update"];
  };
  "/audit-logs": {
    get: operations["AuditLogsController_list"];
  };
  "/audit-logs/{id}": {
    get: operations["AuditLogsController_get"];
  };
  "/recovery-shares": {
    get: operations["RecoverySharesController_list"];
    post: operations["RecoverySharesController_create"];
  };
  "/recovery-shares/{id}": {
    get: operations["RecoverySharesController_get"];
    delete: operations["RecoverySharesController_remove"];
    patch: operations["RecoverySharesController_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ErrorDto: {
      /** @example 400 */
      statusCode: number;
      /** @example Bad Request */
      message: string;
      /** @example Validation failed */
      error?: string;
    };
    RegisterDto: {
      name: string;
      email: string;
      phone: string;
      password: string;
      invitation_token?: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    ForgotPasswordDto: Record<string, never>;
    ResetPasswordDto: Record<string, never>;
    VerifyEmailDto: {
      token: string;
    };
    StartEventDto: {
      /** Format: uuid */
      vault_id: string;
    };
    OrchestratorDecisionDto: {
      /** Format: uuid */
      vault_id: string;
      /** @enum {string} */
      decision: "Confirm" | "Deny";
      signature?: string;
    };
    CreateVaultDto: {
      /** @description Vault display name */
      name?: string;
      /** @description Optional vault description */
      description?: string;
      /** @default false */
      is_demo?: boolean;
      /** @default 2 */
      quorum_threshold?: number;
      /** @default 5 */
      max_verifiers?: number;
      /** @default 60 */
      heartbeat_timeout_days?: number;
      /** @default 24 */
      grace_hours?: number;
    };
    UpdateVaultSettingsDto: {
      quorum_threshold?: number;
      max_verifiers?: number;
      heartbeat_timeout_days?: number;
      grace_hours?: number;
      /** @description Optional primary verifier id */
      primary_verifier_id?: string;
    };
    VerifierMemberDto: {
      /**
       * Format: uuid
       * @description Пусто у приглашения, ещё не принятого аккаунтом
       */
      user_id?: Record<string, unknown> | null;
      /**
       * Format: uuid
       * @description Заполнено у ожидающего приглашения
       */
      invitation_id?: Record<string, unknown> | null;
      email: string;
      name?: Record<string, unknown> | null;
      /** @enum {string} */
      role: "Owner" | "Verifier" | "Admin";
      /** @enum {string} */
      status: "Invited" | "Active" | "Revoked";
      is_primary: boolean;
      expires_at?: Record<string, unknown> | null;
      /** Format: date-time */
      added_at: string;
    };
    InviteVerifierDto: {
      /** Format: uuid */
      vault_id: string;
      /** @description Email приглашаемого верификатора */
      email: string;
      /**
       * @description Срок действия в часах (по умолчанию 7 суток, максимум 30)
       * @default 168
       */
      expires_in_hours?: number;
    };
    InvitationCreatedDto: {
      /** Format: uuid */
      id: string;
      email: string;
      /** @enum {string} */
      role: "Owner" | "Verifier" | "Admin";
      /** Format: date-time */
      expires_at: string;
    };
    AcceptInvitationDto: {
      /** @description Одноразовый токен из письма-приглашения */
      token: string;
    };
    InvitationPreviewDto: {
      email: string;
      /** Format: date-time */
      expires_at: string;
      /** @description Есть ли уже учётная запись с этим адресом: если да, нужно войти, иначе — зарегистрироваться */
      has_account: boolean;
    };
    StartVerificationEventDto: {
      vault_id: string;
    };
    VerificationDecisionDto: {
      signature?: string;
    };
    CreateBlockDto: {
      /** Format: uuid */
      vault_id: string;
      /**
       * @description Только текстовый блок; file и url не поддерживаются
       * @enum {string}
       */
      type: "text";
      /** @description Wrapped DEK (base64 or JWE compact) */
      dek_wrapped: string;
      /** @description Arbitrary JSON metadata (stringified or object) */
      metadata?: Record<string, never>;
      /** @default [] */
      tags?: string[];
      /** @description Encrypted payload size in bytes */
      size?: number;
      checksum?: string;
      /** @default false */
      is_public?: boolean;
    };
    AssignRecipientDto: {
      /** Format: uuid */
      recipient_id: string;
      /** @description DEK wrapped for this recipient (base64 or JWE compact) */
      dek_wrapped_for_recipient: string;
      /** @description Отпечаток SHA-256 (hex) ключа, под который упакован DEK. Принимается, только если равен подтверждённому владельцем отпечатку получателя */
      key_fingerprint: string;
    };
    CreateRecipientDto: {
      /** @description Идентификатор сейфа */
      vault_id: string;
      /** @description Email получателя (уникален в пределах сейфа). Ключ получатель заявляет сам, владелец его не задаёт */
      contact: string;
    };
    RecipientDto: {
      /** Format: uuid */
      id: string;
      /**
       * Format: uuid
       * @description Получатель принадлежит одному сейфу
       */
      vault_id: string;
      contact: string;
      /**
       * @description Invited — ключа нет; KeyClaimed — заявлен получателем, не подтверждён владельцем; KeyConfirmed — отпечаток подтверждён владельцем
       * @enum {string}
       */
      key_status: "Invited" | "KeyClaimed" | "KeyConfirmed";
      /** @description Заявленный получателем публичный ключ */
      public_key: string | null;
      /** @description SHA-256 (hex) заявленного ключа; владелец сверяет его с получателем вне сервера */
      key_fingerprint: string | null;
      /** Format: date-time */
      key_confirmed_at: string | null;
      /** Format: date-time */
      created_at: string;
    };
    ClaimKeyDto: {
      /** @description Публичный ключ получателя; пара создаётся в браузере получателя, приватная часть на сервер не передаётся */
      pubkey: string;
    };
    ClaimKeyResultDto: {
      /** @description SHA-256 (hex) ключа: его получатель сообщает владельцу вне сервера */
      key_fingerprint: string;
      /** @description Сколько назначений на этот адрес получили ключ (сейфов, где вас назначили получателем) */
      recipients: number;
    };
    ConfirmKeyDto: {
      /** @description Отпечаток SHA-256 (hex, пробелы и двоеточия допускаются), который владелец сверил с получателем вне сервера */
      key_fingerprint: string;
    };
    UpdatePublicLinkDto: {
      enabled: boolean;
      publish_from?: string;
      publish_until?: Record<string, never>;
      max_views?: Record<string, unknown> | null;
    };
    UpdateHeartbeatDto: {
      /** @enum {string} */
      method?: "auto" | "manual";
      /** @description Порог неактивности владельца в днях, после которого верификатор может начать процесс (0 — без порога); общая настройка сейфа */
      timeout_days?: number;
    };
    HeartbeatPingDto: {
      /** Format: uuid */
      vault_id: string;
      /** @enum {string} */
      method?: "auto" | "manual";
    };
    UserDto: {
      id: string;
      email: string;
      phone?: string;
      twoFaEnabled: boolean;
      /**
       * Format: date-time
       * @description Когда подтверждён адрес; null — не подтверждён
       */
      emailVerifiedAt: string | null;
      /** @enum {string} */
      role: "Owner" | "Verifier" | "Admin";
      locale: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateUserDto: {
      email: string;
      phone?: string;
      passwordHash?: string;
      passkeyPub?: string;
      /** @default false */
      twoFaEnabled?: boolean;
      /**
       * @default Owner
       * @enum {string}
       */
      role?: "Owner" | "Verifier" | "Admin";
      /** @default ru-RU */
      locale?: string;
    };
    UpdateUserDto: {
      email?: string;
      phone?: string;
      passwordHash?: string;
      passkeyPub?: string;
      /** @default false */
      twoFaEnabled?: boolean;
      /**
       * @default Owner
       * @enum {string}
       */
      role?: "Owner" | "Verifier" | "Admin";
      /** @default ru-RU */
      locale?: string;
    };
    CreatePlanDto: {
      /** @enum {string} */
      tier: "Free" | "Pro" | "Business";
      limits: Record<string, never>;
    };
    UpdatePlanDto: {
      /** @enum {string} */
      tier?: "Free" | "Pro" | "Business";
      limits?: Record<string, never>;
    };
    CreateSubscriptionDto: {
      userId: string;
      planId: string;
      /** @enum {string} */
      status: "trial" | "active" | "canceled";
      currentPeriodEnd: string;
    };
    UpdateSubscriptionDto: {
      userId?: string;
      planId?: string;
      /** @enum {string} */
      status?: "trial" | "active" | "canceled";
      currentPeriodEnd?: string;
    };
    CreateRecoveryShareDto: {
      vaultId: string;
      shareIndex: number;
      shareCipher: string;
    };
    UpdateRecoveryShareDto: {
      vaultId?: string;
      shareIndex?: number;
      shareCipher?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AuthController_register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_forgotPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_resetPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_verifyEmail: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_resendVerification: {
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuthController_me: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  OrchestratorController_start: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartEventDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  OrchestratorController_cancel: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartEventDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  OrchestratorController_decide: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrchestratorDecisionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VaultsController_list: {
    parameters: {
      query: {
        cursor: string;
        limit: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VaultsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateVaultDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VaultsController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VaultsController_updateSettings: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateVaultSettingsDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerifiersController_list: {
    parameters: {
      query: {
        vault_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["VerifierMemberDto"][];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerifiersController_invite: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteVerifierDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["InvitationCreatedDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Адрес и признак аккаунта по токену приглашения (без входа) */
  VerifiersController_preview: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["InvitationPreviewDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerifiersController_accept: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AcceptInvitationDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["VerifierMemberDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerifiersController_revokeInvitation: {
    parameters: {
      path: {
        invitationId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerifiersController_revokeMember: {
    parameters: {
      path: {
        vaultId: string;
        userId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_list: {
    parameters: {
      query?: {
        /** @description Без vault_id — события доступных вам сейфов */
        vault_id?: string;
        /** @description verifier — только сейфы, где вы активный верификатор */
        as?: "verifier";
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_start: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartVerificationEventDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_cancel: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_confirm: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerificationDecisionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  VerificationEventsController_deny: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerificationDecisionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  BlocksController_list: {
    parameters: {
      query: {
        vault_id: string;
        cursor: string;
        limit: number;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  BlocksController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBlockDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  BlocksController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  BlocksController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** List recipients assigned to a block */
  BlocksController_listRecipients: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  /** Assign a recipient to a block */
  BlocksController_assignRecipient: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignRecipientDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecipientsController_search: {
    parameters: {
      query: {
        /** @description Идентификатор сейфа */
        vault_id: string;
        /** @description Подстрока для поиска по contact */
        q?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RecipientDto"][];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecipientsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRecipientDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RecipientDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecipientsController_claimKey: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClaimKeyDto"];
      };
    };
    responses: {
      /** @description Получатель заявляет свой публичный ключ для всех сейфов, где его адрес назначен получателем */
      200: {
        content: {
          "application/json": components["schemas"]["ClaimKeyResultDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecipientsController_confirmKey: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmKeyDto"];
      };
    };
    responses: {
      /** @description Владелец подтверждает отпечаток ключа, сверенный с получателем вне сервера */
      201: {
        content: {
          "application/json": components["schemas"]["RecipientDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PublicLinksController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PublicLinksController_upsert: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePublicLinkDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PublicLinksController_disable: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  HeartbeatsController_getConfig: {
    parameters: {
      path: {
        vaultId: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  HeartbeatsController_updateConfig: {
    parameters: {
      path: {
        vaultId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateHeartbeatDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  HeartbeatsController_ping: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["HeartbeatPingDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  HealthController_healthz: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  HealthController_readyz: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  UsersController_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"][];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  UsersController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  UsersController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  UsersController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  UsersController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserDto"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PlansController_list: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PlansController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePlanDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PlansController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PlansController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  PlansController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePlanDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  SubscriptionsController_list: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  SubscriptionsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSubscriptionDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  SubscriptionsController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  SubscriptionsController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  SubscriptionsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSubscriptionDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuditLogsController_list: {
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  AuditLogsController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecoverySharesController_list: {
    parameters: {
      query: {
        vault_id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecoverySharesController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRecoveryShareDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecoverySharesController_get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecoverySharesController_remove: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
  RecoverySharesController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRecoveryShareDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      403: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
      500: {
        content: {
          "application/json": components["schemas"]["ErrorDto"];
        };
      };
    };
  };
}
