name: Bug report
description: Сообщение об ошибке
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Шаги воспроизведения
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Окружение (версия, бранч, браузер и т.д.)
