openapi: 3.1.0
info:
  title: AfterLight API
  version: 0.1.0
servers:
  - url: https://api.afterlight.example/v1
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  headers:
    Idempotency-Key:
      description: Deduplicate POST/PUT operations
      schema: { type: string }
  parameters:
    Cursor:
      name: cursor
      in: query
      schema: { type: string }
    Limit:
      name: limit
      in: query
      schema: { type: integer, minimum: 1, maximum: 200, default: 50 }
  schemas:
    Error:
      type: object
      properties:
        code: { type: string }
        message: { type: string }
        details: { type: object, additionalProperties: true }
    User:
      type: object
      properties:
        id: { type: string, format: uuid }
        email: { type: string }
        role: { type: string, enum: [User, Admin] }
    Vault:
      type: object
      properties:
        id: { type: string, format: uuid }
        status: { type: string, enum: [Active, Triggered, PendingGrace, Released, Closed] }
        quorum_threshold: { type: integer, minimum: 3, maximum: 5, default: 3 }
        max_verifiers: { type: integer, minimum: 3, maximum: 5, default: 5 }
        heartbeat_timeout_days: { type: integer, default: 60 }
        grace_hours: { type: integer, default: 24 }
        is_demo: { type: boolean, default: false }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
    VaultCreate:
      type: object
      properties:
        is_demo: { type: boolean, default: false }
        quorum_threshold: { type: integer, minimum: 3, maximum: 5, default: 3 }
        max_verifiers: { type: integer, minimum: 3, maximum: 5, default: 5 }
        heartbeat_timeout_days: { type: integer, default: 60 }
        grace_hours: { type: integer, default: 24 }
      required: []
    Block:
      type: object
      properties:
        id: { type: string, format: uuid }
        vault_id: { type: string, format: uuid }
        type: { type: string, enum: [text, file, url] }
        tags: { type: array, items: { type: string } }
        size: { type: integer }
        checksum: { type: string }
        is_public: { type: boolean, default: false }
        created_at: { type: string, format: date-time }
    BlockCreateMultipart:
      type: object
      properties:
        vault_id: { type: string, format: uuid }
        type: { type: string, enum: [text, file, url] }
        content: { type: string, format: binary, description: "client-side encrypted payload or envelope (max ~50 MB in MVP)" }
        metadata: { type: string, description: "JSON (stringified) with client-side metadata" }
        tags: { type: array, items: { type: string } }
        is_public: { type: boolean, default: false }
      required: [vault_id, type]
    Recipient:
      type: object
      properties:
        id: { type: string, format: uuid }
        contact: { type: string, description: "email (phone optional)" }
        pubkey: { type: string, nullable: true }
        verification_status: { type: string, enum: [Invited, Verified, Blocked] }
    RecipientAssign:
      type: object
      properties:
        recipient_id: { type: string, format: uuid }
        dek_wrapped_for_recipient: { type: string }
      required: [recipient_id, dek_wrapped_for_recipient]
    Verifier:
      type: object
      properties:
        id: { type: string, format: uuid }
        contact: { type: string, description: "email (phone optional)" }
        kyc_level: { type: string, enum: [None, Basic, Enhanced] }
        role_status: { type: string, enum: [Invited, Active, Revoked] }
        is_primary: { type: boolean, default: false }
    VerifierInvite:
      type: object
      properties:
        vault_id: { type: string, format: uuid }
        contact: { type: string, description: "email (phone optional)" }
        channel: { type: string, enum: [email, sms], default: email }
        expires_in_hours: { type: integer, default: 168, description: "default 7 days" }
      required: [vault_id, contact]
    VerificationEvent:
      type: object
      properties:
        id: { type: string, format: uuid }
        vault_id: { type: string, format: uuid }
        state: { type: string, enum: [Draft, Submitted, Confirming, Disputed, QuorumReached, HeartbeatTimeout, Grace, Finalized] }
        quorum_required: { type: integer }
        confirms_count: { type: integer }
        denies_count: { type: integer }
        created_at: { type: string, format: date-time }
    DecisionRequest:
      type: object
      properties:
        decision: { type: string, enum: [Confirm, Deny] }
        signature: { type: string, description: "verifier's signature over event payload (optional in MVP)" }
      required: [decision]
    HeartbeatPing:
      type: object
      properties:
        vault_id: { type: string, format: uuid }
        method: { type: string, enum: [auto, manual], default: manual }
      required: [vault_id]
    PublicLink:
      type: object
      properties:
        id: { type: string, format: uuid }
        block_id: { type: string, format: uuid }
        enabled: { type: boolean }
        publish_from: { type: string, format: date-time }
        publish_until: { type: string, format: date-time, nullable: true }
        url: { type: string }
        max_views: { type: integer, nullable: true }
        views_count: { type: integer }
    PublicLinkUpdate:
      type: object
      properties:
        enabled: { type: boolean }
        publish_from: { type: string, format: date-time }
        publish_until: { type: string, format: date-time, nullable: true }
        max_views: { type: integer, nullable: true }
      required: [enabled]
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /auth/register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, phone]
              properties:
                name: { type: string }
                email: { type: string }
                phone: { type: string }
                password: { type: string }
                role: { type: string, enum: [Owner, Verifier, Admin] }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /auth/login:
    post:
      summary: Login, sets JWT cookie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              description: JWT httpOnly cookie
              schema: { type: string }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /auth/logout:
    post:
      summary: Clear auth cookies
      responses:
        '200': { description: Logged out }
  /auth/me:
    get:
      summary: Get current user
      responses:
        '200':
          description: Current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401': { description: Unauthorized }
  /vaults:
    get:
      summary: List vaults
      responses:
        '200': { description: OK }
    post:
      summary: Create vault
      responses:
        '201': { description: Created }
  /blocks:
    get:
      summary: List blocks by vault
      responses:
        '200': { description: OK }
    post:
      summary: Create block (multipart)
      responses:
        '201': { description: Created }
  /recipients:
    post:
      summary: Create recipient
      responses:
        '201': { description: Created }
  /blocks/{id}/recipients:
    post:
      summary: Assign recipient
      responses:
        '201': { description: Created }
  /blocks/{id}/public:
    get:
      summary: Get public link settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicLink'
    put:
      summary: Enable or update public link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublicLinkUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicLink'
    delete:
      summary: Disable public link
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicLink'
  /verifiers/invitations:
    post:
      summary: Invite verifier
      responses:
        '201': { description: Created }
  /verification-events:
    post:
      summary: Start verification event
      responses:
        '201': { description: Created }
  /verification-events/{id}/confirm:
    post:
      summary: Verifier confirms
      responses:
        '204': { description: No Content }
  /verification-events/{id}/deny:
    post:
      summary: Verifier denies
      responses:
        '204': { description: No Content }
  /heartbeats/ping:
    post:
      summary: Owner heartbeat ping
      responses:
        '204': { description: No Content }
  /users:
    get:
      summary: List users
      responses:
        '200': { description: OK }
    post:
      summary: Create user
      responses:
        '201': { description: Created }
  /users/{id}:
    get:
      summary: Get user
      responses:
        '200': { description: OK }
    patch:
      summary: Update user
      responses:
        '200': { description: OK }
    delete:
      summary: Delete user
      responses:
        '204': { description: No Content }
  /plans:
    get:
      summary: List plans
      responses:
        '200': { description: OK }
    post:
      summary: Create plan
      responses:
        '201': { description: Created }
  /plans/{id}:
    get:
      summary: Get plan
      responses:
        '200': { description: OK }
    patch:
      summary: Update plan
      responses:
        '200': { description: OK }
    delete:
      summary: Delete plan
      responses:
        '204': { description: No Content }
  /subscriptions:
    get:
      summary: List subscriptions
      responses:
        '200': { description: OK }
    post:
      summary: Create subscription
      responses:
        '201': { description: Created }
  /subscriptions/{id}:
    get:
      summary: Get subscription
      responses:
        '200': { description: OK }
    patch:
      summary: Update subscription
      responses:
        '200': { description: OK }
    delete:
      summary: Delete subscription
      responses:
        '204': { description: No Content }
  /audit-logs:
    get:
      summary: List audit logs
      responses:
        '200': { description: OK }
    post:
      summary: Create audit log entry
      responses:
        '201': { description: Created }
  /audit-logs/{id}:
    get:
      summary: Get audit log entry
      responses:
        '200': { description: OK }
    patch:
      summary: Update audit log entry
      responses:
        '200': { description: OK }
    delete:
      summary: Delete audit log entry
      responses:
        '204': { description: No Content }
  /recovery-shares:
    get:
      summary: List recovery shares
      responses:
        '200': { description: OK }
    post:
      summary: Create recovery share
      responses:
        '201': { description: Created }
  /recovery-shares/{id}:
    get:
      summary: Get recovery share
      responses:
        '200': { description: OK }
    patch:
      summary: Update recovery share
      responses:
        '200': { description: OK }
    delete:
      summary: Delete recovery share
      responses:
        '204': { description: No Content }
