name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: |
          cd apps/api && pnpm i || true
          cd ../../apps/web && pnpm i || true
      - name: Build API
        run: |
          cd apps/api && pnpm build || true
