name: seed

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Напиши: prod (подтверждаю сид ПРОД БД)'
        required: true
        default: 'no'

concurrency:
  group: seed-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  seed:
    if: ${{ inputs.confirm == 'prod' }}
    runs-on: self-hosted
    env:
      NS: afterlight
    steps:
      - uses: actions/checkout@v4
      - name: kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          printf "%s" "${{ secrets.KUBECONFIG_AFTERLIGHT }}" > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
      - name: Create seed Job
        id: create
        run: |
          JOB_NAME=$(kubectl -n "$NS" create -f k8s/job-prisma-seed.yaml -o jsonpath='{.metadata.name}')
          echo "job=${JOB_NAME}" >> $GITHUB_OUTPUT

      - name: Wait for completion & show logs
        run: |
          kubectl -n "$NS" wait --for=condition=complete --timeout=10m job/${{ steps.create.outputs.job }}
          kubectl -n "$NS" logs job/${{ steps.create.outputs.job }} --all-containers --tail=-1

      - name: Cleanup
        if: always()
        run: kubectl -n "$NS" delete job/${{ steps.create.outputs.job }} --ignore-not-found=true
