name: docker-api

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'Dockerfile.api'
      - '.github/workflows/docker-api.yml'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Sanity check
        run: |
          test -f Dockerfile.api
          test -f apps/api/package.json
          test -f apps/api/prisma/schema.prisma

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          # снимите комментарий на один прогон, если нужно убить кэш:
          # no-cache: true
          tags: |
            ghcr.io/grayhex/afterlight-api:latest
            ghcr.io/grayhex/afterlight-api:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
