name: Build & Push
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanity check
        run: |
          test -f Dockerfile.api || (echo "Dockerfile.api not found" && exit 1)
          test -f apps/api/package.json || (echo "apps/api/package.json not found" && exit 1)
          test -f apps/api/prisma/schema.prisma || (echo "apps/api/prisma/schema.prisma not found" && exit 1)

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api          # <-- указываем наш файл
          push: true
          no-cache: true         # <— добавь временно
          tags: |
            ghcr.io/grayhex/afterlight-api:latest
            ghcr.io/grayhex/afterlight-api:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
