name: docker-api

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/afterlight-api:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/afterlight-api:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/afterlight-api:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/afterlight-api:cache,mode=max
