name: docker-web
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/afterlight-web:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/afterlight-web:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/afterlight-web:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/afterlight-web:cache,mode=max
