name: docker-web

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - 'Dockerfile.web'
      - '.github/workflows/docker-web.yml'
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanity check
        run: |
          test -f Dockerfile.web
          test -f apps/web/package.json

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.web
          push: true
          # no-cache: true  # uncomment once if you need to bust cache
          tags: |
            ghcr.io/grayhex/afterlight-web:latest
            ghcr.io/grayhex/afterlight-web:main
            ghcr.io/grayhex/afterlight-web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
